src/Entity/Affectation.php
<?php

namespace App\Entity;

use App\Repository\AffectationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AffectationRepository::class)]
class Affectation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Collaborateur $collaborateur = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Restaurant $restaurant = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Fonction $fonction = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?\DateTimeImmutable $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $date_fin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCollaborateur(): ?Collaborateur
    {
        return $this->collaborateur;
    }

    public function setCollaborateur(?Collaborateur $collaborateur): static
    {
        $this->collaborateur = $collaborateur;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): static
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getFonction(): ?Fonction
    {
        return $this->fonction;
    }

    public function setFonction(?Fonction $fonction): static
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeImmutable
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeImmutable $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeImmutable
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeImmutable $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }
}

src/Entity/Collaborateur.php
<?php

namespace App\Entity;

use App\Repository\CollaborateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: CollaborateurRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Collaborateur implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 150)]
    private ?string $prenom = null;

    #[ORM\Column]
    private ?bool $isadmin = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?\DateTimeImmutable $date_embauche = null;

    /**
     * @var Collection<int, Affectation>
     */
    #[ORM\OneToMany(targetEntity: Affectation::class, mappedBy: 'collaborateur')]
    private Collection $affectations;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    public function __construct()
    {
        $this->affectations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function isadmin(): ?bool
    {
        return $this->isadmin;
    }

    public function setAdmin(bool $isadmin): static
    {
        $this->isadmin = $isadmin;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeImmutable
    {
        return $this->date_embauche;
    }

    public function setDateEmbauche(\DateTimeImmutable $date_embauche): static
    {
        $this->date_embauche = $date_embauche;

        return $this;
    }

    /**
     * @return Collection<int, Affectation>
     */
    public function getAffectations(): Collection
    {
        return $this->affectations;
    }

    public function addAffectation(Affectation $affectation): static
    {
        if (!$this->affectations->contains($affectation)) {
            $this->affectations->add($affectation);
            $affectation->setCollaborateur($this);
        }

        return $this;
    }

    public function removeAffectation(Affectation $affectation): static
    {
        if ($this->affectations->removeElement($affectation)) {
            // set the owning side to null (unless already changed)
            if ($affectation->getCollaborateur() === $this) {
                $affectation->setCollaborateur(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Controller/CollaborateurController.php
<?php

namespace App\Controller;

use App\Entity\Fonction;
use App\Form\SearchType;
use App\Entity\Affectation;
use App\Entity\Collaborateur;
use App\Form\AffectationType;
use App\Form\CollaborateurType;
use App\Form\SearchAffectationType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\AffectationRepository;
use App\Repository\CollaborateurRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/collaborateur')]
class CollaborateurController extends AbstractController
{
    /**
     * Liste des collaborateurs
     */
    #[Route('', name: 'collaborateur_index')]
    public function index(Request $request, CollaborateurRepository $collaborateurRepository, PaginatorInterface $paginator): Response
    {
        // On récupère le formulaire de recherche
        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);
        // Si on a les filtres en paramètres, on les récupère (filtre en GET ou formulaire search)
        $search = ($form->isSubmitted() && $form->isValid()) ? $form->get('search')->getData() : "";
        $noAffectation = (!is_null($request->query->get("affected")) && $request->query->get("affected") == "false") ? true : false;

        // On récupère la requête pour afficher les collaborateurs (avec les filtres en paramètres)
        $queryBuilder = $collaborateurRepository->searchCollaborateurs($search,$noAffectation);

        // Utiliser KnpPaginator pour paginer les résultats
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
        );

        return $this->render('collaborateur/index.html.twig', [
            'pagination' => $pagination,
            'formSearch' => $form
        ]);
    }

    /**
     * Affiche le détail d'un collaborateur
     */
    #[Route('/{id}/detail', name: 'collaborateur_detail')]
    public function detail(Collaborateur $collaborateur, AffectationRepository $affectationRepository, Request $request, PaginatorInterface $paginator): Response
    {
        // On récupère le formulaire de filtre d'affectations
        $form = $this->createForm(SearchAffectationType::class);
        $form->handleRequest($request);
        // Si on a le formulaire de filtre soumis, on récupère les valeurs
        $fonction = ($form->isSubmitted() && !is_null($form->get('fonction')->getData())) ? $form->get('fonction')->getData() : new Fonction;
        $date_affectation = ($form->isSubmitted() && !is_null($form->get('date')->getData())) ? $form->get('date')->getData() : null;

        // On récupère la requête pour afficher les affectations sur collaborateurs (avec les filtres en paramètres)
        $queryBuilder = $affectationRepository->searchAffectationsCollaborateur($collaborateur,$fonction,$date_affectation);

        // Utiliser KnpPaginator pour paginer les résultats
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1)
        );
        
        return $this->render('collaborateur/detail.html.twig', [
            "collaborateur" => $collaborateur,
            "pagination" => $pagination,
            "formSearch" => $form
        ]);
    }

    /**
     * Gestion de la création d'un collaborateur
     */
    #[Route('/new', name: 'collaborateur_new')]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        // Création du formulaire
        $collaborateur = new Collaborateur();
        $form = $this->createForm(CollaborateurType::class, $collaborateur);
        $form->handleRequest($request);

        // Si le formulaire a été soumis et qu'il est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // On met les paramètres maquants par défaut
            $collaborateur->setAdmin(false);
            $collaborateur->setVerified(true);
            // On récupère la photo
            $image = $form->get('photo')->getData();
            // Si une photo est bien présente
            if ($image) {
                // On récupère le fichier
                $nomFichier = uniqid().'.'.$image->guessExtension();
                $image->move(
                    $this->getParameter('images_directory_collaborateur'),
                    $nomFichier
                );
                // On affecte la photo à l'utilisateur
                $collaborateur->setPhoto($nomFichier);
            }

            // Insertion en base de données
            // On utilise l'entity manager
            $em->persist($collaborateur);
            $em->flush();
            //On ajoute un message flash
            $this->addFlash('success','Le collaborateur a été enregistré avec succès');
            // Redirection vers la liste des collaborateurs
            return $this->redirectToRoute('collaborateur_index');
        }

        return $this->render('collaborateur/create.html.twig', [
            'form' => $form
        ]);
    }

    /**
     * Gestion de la modification d'un collaborateur
     */
    #[Route('/{id}/edit', name: 'collaborateur_edit')]
    public function edit(Collaborateur $collaborateur, Request $request, EntityManagerInterface $em, Filesystem $filesystem): Response
    {
        // Création du formulaire, chargé avec le collaborateur
        $form = $this->createForm(CollaborateurType::class, $collaborateur);
        $form->handleRequest($request);

        // Si le formulaire a été soumis et qu'il est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère la photo
            $image = $form->get('photo')->getData();
            // Si une photo est bien présente
            if ($image) {
                // On récupère le fichier
                $nomFichier = uniqid().'.'.$image->guessExtension();
                $image->move(
                    $this->getParameter('images_directory_collaborateur'),
                    $nomFichier
                );

                // On supprime l'ancienne photo
                $filesystem->remove($this->getParameter('images_directory_collaborateur').'/'.$collaborateur->getPhoto($nomFichier));

                // On attache la photo au collaborateur
                $collaborateur->setPhoto($nomFichier);
            }

            // Insertion en base de données
            // On utilise l'entity manager
            $em->persist($collaborateur);
            $em->flush();
            //On ajoute un message flash
            $this->addFlash('success','Le collaborateur a été modifié avec succès');
            // Redirection vers le détail de l'utilisateur
            return $this->redirectToRoute('collaborateur_detail',['id' => $collaborateur->getId()]);
        }

        return $this->render('collaborateur/edit.html.twig', [
            'form' => $form,
            'collaborateur' => $collaborateur
        ]);
    }

    /**
     * Suppression d'un collaborateur
     */
    #[Route('/{id}', name: 'collaborateur_delete', methods: ['DELETE'])]
    public function delete(Collaborateur $collaborateur, Request $request, EntityManagerInterface $em): JsonResponse
    {
        // On récupère les données JSON
        $data = json_decode($request->getContent(), true);
        
        // On vérifie le token CSRF
        if ($this->isCsrfTokenValid('delete'.$collaborateur->getId(), $data['_token'])) {
            // On supprime le collaborateur
            $em->remove($collaborateur);
            $em->flush();

            //On ajoute un message flash
            $this->addFlash('success','Le collaborateur a été supprimé avec succès');

            // On créé le retour
            $response = [
                'status' => 'success',
                'redirect' => '/collaborateur'
            ];
        } else {
            //On ajoute un message flash
            $this->addFlash('error','Le collaborateur n\'a pas pu être supprimé');
            // On créé le retour
            $response = [
                'status' => 'error',
            ];
        }

        return new JsonResponse($response);
    }

    /**
     * Affecte un collaborateur
     */
    #[Route('/{id}/affectations/add', name: 'collaborateur_affected')]
    public function affected(Collaborateur $collaborateur, Request $request, EntityManagerInterface $em): Response
    {
        // Création du formulaire
        $affectation = new Affectation();
        $form = $this->createForm(AffectationType::class,$affectation);
        $form->handleRequest($request);

        // Si le formulaire a été soumis et qu'il est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // On définit l'utilisateur de l'affectation
            $affectation->setCollaborateur($collaborateur);
            // Insertion en base de données
            // On utilise l'entity manager
            $em->persist($affectation);
            $em->flush();
            //On ajoute un message flash
            $this->addFlash('success','Le collaborateur a été affecté au restaurant avec succès');
            // Redirection vers la page de détail du collaborateur
            return $this->redirectToRoute('collaborateur_detail',['id' => $collaborateur->getId()]);
        }

        return $this->render('collaborateur/affected.html.twig', [
            'form' => $form,
            'collaborateur' => $collaborateur
        ]);
    }

    /**
     * Modifie l'affectation d'un collaborateur
     */
    #[Route('/{collaborateur}/affectation/{affectation}/edit', name: 'collaborateur_affectation_edit')]
    public function affectationEdit(Collaborateur $collaborateur, Affectation $affectation, Request $request, EntityManagerInterface $em): Response
    {

templates/collaborateur/_collaborateur.html.twig
<article class="large-6-12 flex gap justify-between">
	<div class="large-4-12">
		<img class="responsive" src="{{ asset(images_affichage_directory_collaborateur ~ collaborateur.photo) }}" alt="">
	</div>
	<div class="description-article large-8-12 flex gap direction-column justify-between">
		<h3>{{ collaborateur.nom ~ " " ~ collaborateur.prenom }}</h3>
		<p>
			{{ collaborateur.email }}<br/>
			Embauché le {{ collaborateur.dateEmbauche |date('d-m-Y') }}
		</p>
		<div class="flex gap justify-end">
			<a class="button primary" href="{{path('collaborateur_detail',{ "id": collaborateur.id })}}" title="Voir les informations sur le {{ collaborateur.nom ~ " " ~ collaborateur.prenom }}">Voir</a>
		</div>
	</div>
</article>

templates/collaborateur/affected.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full flex gap direction-column align-center">
    <h1>Affectation de {{ collaborateur.nom ~ " " ~ collaborateur.prenom}}</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('collaborateur_detail',{ "id": collaborateur.id }) }}" title="Retour au collaborateur">Retour au collaborateur</a>
    </div>
    <div class="large-6-12">
        {{ form_start(form) }}
        {{ form_row(form.restaurant) }}
        {{ form_row(form.fonction) }}
        {{ form_row(form.dateDebut) }}
        {{ form_widget(form._token) }}
        {{ form_row(form.submit) }}
        {{ form_end(form, {'render_rest': false}) }}
    </div>
</div>
{% endblock %}

templates/collaborateur/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full  flex gap direction-column align-center">
    <h1>Entrée d'un nouveau collaborateur</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('collaborateur_index') }}" title="Retour à la liste">Retour à la liste</a>
    </div>
    <div class="large-6-12">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/collaborateur/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}

<div class="page-container container-full flex gap direction-column align-center justify-center">
    <h1>Informations sur {{ collaborateur.nom ~ " " ~ collaborateur.prenom}}</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('collaborateur_index') }}" title="Retour à la liste">Retour à la liste</a>
    </div>
    <div class="large-12-12 flex gap justify-between">
        <div class="large-2-12">
            <img class="responsive" src="{{ asset(images_affichage_directory_collaborateur ~ collaborateur.photo) }}" alt="">
        </div>
        <div class="description-article large-8-12 flex gap direction-column justify-between">
            <h2>{{ collaborateur.nom ~ " " ~ collaborateur.prenom}}</h2>
            <p>
                {{ collaborateur.email }}<br/>
                Embauché le {{ collaborateur.dateEmbauche |date('d-m-Y') }}
            </p>
            <div class="flex gap justify-end">
                {% if collaborateur.id != app.user.id %}
                    {% if pagination.getTotalItemCount == 0 %}
                    <a id="button_suppresion" class="button third" href="{{ path('collaborateur_delete',{ "id": collaborateur.id }) }}" title="Supprimer le collaborateur">Supprimer</a>
                    {% endif %}
                {% endif %}
                <a class="button primary" href="{{ path('collaborateur_edit',{ "id": collaborateur.id }) }}" title="Modifier le collaborateur">Modifier</a>
            </div>
	    </div>
    </div>
    <div class="separateur"></div>
    <div class="filtres large-12-12 flex justify-center gap">
        {{ form_start(formSearch, {'attr': {'class': 'large-10-12 flex gap align-center'}}) }}
        {{ form_row(formSearch.fonction) }}
        {{ form_row(formSearch.date) }}
        {{ form_row(formSearch._token) }}
        {{ form_row(formSearch.submit) }}
        {{ form_end(formSearch, {'render_rest': false}) }}
    </div>
    <div class="large-12-12 flex gap">
        <a class="button primary" href="{{ path('collaborateur_affected',{ "id": collaborateur.id }) }}" title="Affecter le collaborateur">Nouvelle affectation</a>
    </div>
    <section class="liste-collaborateur large-12-12 flex gap justify-between">
        <table class="large-12-12">
            <thead>
                <tr>
                    <th>Restaurant</th>
                    <th>Poste occupé</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for affectation in pagination.items %}
                <tr>
                    <td><a href="{{ path('restaurant_detail',{ "id": affectation.restaurant.id }) }}" title="Détail du restaurant {{ affectation.restaurant.nom }}">{{ affectation.restaurant.nom }}</a></td>
                    <td>{{ affectation.fonction.intitule }}</td>
                    <td>{{ affectation.dateDebut |date('d-m-Y') }}</td>
                    <td>{% if affectation.dateFin is not null %}{{ affectation.dateFin |date('d-m-Y') }}{% endif %}</td>
                    <td>
                        <a href="{{ path('collaborateur_affectation_edit',{ "collaborateur": collaborateur.id, "affectation": affectation.id }) }}" title="Modifier l'affectation">
                            <img src="{{ asset('images/icons/edit.png') }}" alt="Icone de modification">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
	</section>
	<div class="navigation large-12-12 flex justify-between">
		{{ knp_pagination_render(pagination) }}
        <div>
            {% if pagination.getItemNumberPerPage > pagination.getTotalItemCount %}
            {{ pagination.getTotalItemCount }}
            {% else %}
            {{ pagination.getItemNumberPerPage }}
            {% endif %}
            Résultats par page - Total de
            {{ pagination.getTotalItemCount }}
            résultats
        </div>
	</div>
</div>
<script>
    // Récupère le jeton CSRF
    const csrfToken = '{{ csrf_token('delete' ~ collaborateur.id) }}';
</script>
{% endblock %}

templates/collaborateur/edit.affectation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full flex gap direction-column align-center">
    <h1>Affectation de {{ collaborateur.nom ~ " " ~ collaborateur.prenom}}</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('collaborateur_detail',{ "id": collaborateur.id }) }}" title="Retour au collaborateur">Retour au collaborateur</a>
    </div>
    <div class="large-6-12">
        {{ form_start(form) }}
        {{ form_row(form.restaurant) }}
        {{ form_row(form.fonction) }}
        {{ form_row(form.dateDebut) }}
        {{ form_row(form.dateFin) }}
        {{ form_widget(form._token) }}
        {{ form_row(form.submit) }}
        {{ form_end(form, {'render_rest': false}) }}
    </div>
</div>
{% endblock %}

templates/collaborateur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full  flex gap direction-column align-center">
    <h1>Mettre à jour les informations de {{ collaborateur.prenom }}</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('collaborateur_detail',{ "id": collaborateur.id }) }}" title="Retour au collaborateur">Retour au collaborateur</a>
    </div>
    <div class="large-6-12">
        {{ form_start(form) }}
        {{ form_row(form.nom) }}
        {{ form_row(form.prenom) }}
        {{ form_row(form.email) }}
        {{ form_row(form.dateEmbauche) }}
        <div class="large-12-12 flex gap">
            <div class="large-3-12"><img class="responsive" src="{{ asset(images_affichage_directory_collaborateur ~ collaborateur.photo) }}" alt=""></div>
            <div class="large-9-12">{{ form_row(form.photo) }}</div>
        </div>
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/collaborateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}

<div class="page-container container-full flex gap direction-column align-center">
    <h1>Gestion des collaborateurs de Wakdo</h1>
    <div class="large-12-12 flex gap justify-between">
        <div class="flex gap">
            <a class="button primary" href="{{ path('collaborateur_new') }}" title="Ajouter un nouveau collaborateur">Nouveau collaborateur</a>
            <a class="button primary" href="{{ path('app_register') }}" title="Ajouter un adminsitrateur">Nouvel administrateur</a>
        </div>
        <div class="flex gap">
            <a class="button secondary" href="{{ path('collaborateur_index') }}" title="Ajouter un nouveau collaborateur">Tous</a>
            <a class="button secondary" href="{{ path('collaborateur_index',{ "affected": "false" }) }}" title="Ajouter un nouveau collaborateur">Collaborateurs non-affectés</a>
        </div>
    </div>
    <div class="filtres large-12-12 flex justify-center gap">
        {{ form_start(formSearch, {'attr': {'class': 'large-10-12'}}) }}
        {{ form_widget(formSearch.search, {'attr': {'placeholder': 'Rechercher par nom, prénom ou adresse e-mail...','class': 'large-10-12'}}) }}
        {{ form_end(formSearch) }}
    </div>
    <section class="liste-collaborateur large-12-12 flex gap justify-between">
		{% for collaborateur in pagination.items %}
            {% include "collaborateur/_collaborateur.html.twig" %}
		{% endfor %}
	</section>
	<div class="navigation large-12-12 flex justify-between">
		{{ knp_pagination_render(pagination) }}
        <div>
            {% if pagination.getItemNumberPerPage > pagination.getTotalItemCount %}
            {{ pagination.getTotalItemCount }}
            {% else %}
            {{ pagination.getItemNumberPerPage }}
            {% endif %}
            Résultats par page - Total de
            {{ pagination.getTotalItemCount }}
            résultats
        </div>
	</div>
</div>
{% endblock %}