src/Entity/Affectation.php
<?php

namespace App\Entity;

use App\Repository\AffectationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AffectationRepository::class)]
class Affectation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Collaborateur $collaborateur = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Restaurant $restaurant = null;

    #[ORM\ManyToOne(inversedBy: 'affectations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Fonction $fonction = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE)]
    private ?\DateTimeImmutable $date_debut = null;

    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $date_fin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCollaborateur(): ?Collaborateur
    {
        return $this->collaborateur;
    }

    public function setCollaborateur(?Collaborateur $collaborateur): static
    {
        $this->collaborateur = $collaborateur;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): static
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getFonction(): ?Fonction
    {
        return $this->fonction;
    }

    public function setFonction(?Fonction $fonction): static
    {
        $this->fonction = $fonction;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeImmutable
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeImmutable $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeImmutable
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeImmutable $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }
}

src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RestaurantRepository::class)]
class Restaurant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 10)]
    private ?string $code_postal = null;

    #[ORM\Column(length: 100)]
    private ?string $ville = null;

    /**
     * @var Collection<int, Affectation>
     */
    #[ORM\OneToMany(targetEntity: Affectation::class, mappedBy: 'restaurant')]
    private Collection $affectations;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    public function __construct()
    {
        $this->affectations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection<int, Affectation>
     */
    public function getAffectations(): Collection
    {
        return $this->affectations;
    }

    public function addAffectation(Affectation $affectation): static
    {
        if (!$this->affectations->contains($affectation)) {
            $this->affectations->add($affectation);
            $affectation->setRestaurant($this);
        }

        return $this;
    }

    public function removeAffectation(Affectation $affectation): static
    {
        if ($this->affectations->removeElement($affectation)) {
            // set the owning side to null (unless already changed)
            if ($affectation->getRestaurant() === $this) {
                $affectation->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Form\SearchType;
use App\Entity\Restaurant;
use App\Entity\Affectation;
use App\Form\RestaurantType;
use App\Form\AffectationType;
use App\Form\SearchAffectationType;
use App\Repository\RestaurantRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\AffectationRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/restaurant')]
class RestaurantController extends AbstractController
{
    /**
     * Liste des restaurants (page d'accueil)
     */
    #[Route('', name: 'app_accueil')]
    public function index(Request $request, RestaurantRepository $restaurantRepository, PaginatorInterface $paginator): Response
    {
        // On récupère la requête pour lister les restaurants 
        $queryBuilder = $restaurantRepository->createQueryBuilder('r')->orderBy('r.id','DESC');

        // On récupère le formulaire de recherche
        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);

        // Si le formulaire de recherche est soumis et valide
        if($form->isSubmitted() && $form->isValid()) {
            // On ajoute les paramètres de recherche à la requête
            $queryBuilder->andWhere(
                $queryBuilder->expr()->orX(
                    $queryBuilder->expr()->like('UPPER(r.nom)', ':search'),
                    $queryBuilder->expr()->like('UPPER(r.ville)', ':search'),
                    $queryBuilder->expr()->like('UPPER(r.code_postal)', ':search')
                )
            )
            ->setParameter(':search','%'.strtoupper($form->get('search')->getData()).'%');
        }

        // Utiliser KnpPaginator pour paginer les résultats
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
        );

        return $this->render('restaurant/index.html.twig', [
            'pagination' => $pagination,
            'formSearch' => $form
        ]);
    }

    /**
     * Affiche le détail d'un restaurant
     */
    #[Route('/{id}/detail', name: 'restaurant_detail')]
    public function detail(Restaurant $restaurant, Request $request, RestaurantRepository $restaurantRepository, PaginatorInterface $paginator, EntityManagerInterface $em): Response
    {
        // On récupère le formulaire de recherche des affectations
        $form = $this->createForm(SearchAffectationType::class);
        $form->handleRequest($request);

        // Si le formulaire de recherche des affectations est soumis et valide
        if($form->isSubmitted() && $form->isValid()) {
            // On récupère les paramètres
            $search = $form->get('search')->getData();
            $fonction = $form->get('fonction')->getData();
            $date_affectation = $form->get('date')->getData();
        }
        else {
            $search = "";
            $fonction = "";
            $date_affectation = "";
        }

        // On récupère la requête pour voir les affectations du restaurant
        $queryBuilder = $restaurantRepository->searchAffectations($restaurant, $search, $fonction, $date_affectation, $em);

        // Utiliser KnpPaginator pour paginer les résultats
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
        );

        return $this->render('restaurant/detail.html.twig', [
            "restaurant" => $restaurant,
            "pagination" => $pagination,
            "formSearch" => $form
        ]);
    }

    /**
     * Gestion de la création d'un restaurant
     */
    #[Route('/new', name: 'restaurant_new')]
    public function create(Request $request, EntityManagerInterface $em): Response
    {
        // Création du formulaire
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        // Si le formulaire a été soumis et qu'il est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère la photo
            $image = $form->get('photo')->getData();
            // Si une photo est bien présente
            if ($image) {
                // On récupère le fichier
                $nomFichier = uniqid().'.'.$image->guessExtension();
                $image->move(
                    $this->getParameter('images_directory_restaurant'),
                    $nomFichier
                );
                // On attache la photo au restaurant
                $restaurant->setPhoto($nomFichier);
            }

            // Insertion en base de données
            // On utilise l'entity manager
            $em->persist($restaurant);
            $em->flush();
            //On ajoute un message flash
            $this->addFlash('success','Le restaurant a été enregistré avec succès');
            // Redirection vers la liste des restaurants (accueil)
            return $this->redirectToRoute('app_accueil');
        }

        return $this->render('restaurant/create.html.twig', [
            'form' => $form
        ]);
    }

    /**
     * Gestion de la modification d'un restaurant
     */
    #[Route('/{id}/edit', name: 'restaurant_edit')]
    public function edit(Restaurant $restaurant, Request $request, EntityManagerInterface $em, Filesystem $filesystem, RestaurantRepository $restaurantRepository, PaginatorInterface $paginator): Response
    {
        // On récupère le formulaire de recherche des affectations
        $formSearch = $this->createForm(SearchAffectationType::class);
        $formSearch->handleRequest($request);
        // Si le formulaire est soumis et valide
        if($formSearch->isSubmitted() && $formSearch->isValid()) {
            // On récupère les valeurs
            $search = $formSearch->get('search')->getData();
            $fonction = $formSearch->get('fonction')->getData();
            $date_affectation = $formSearch->get('date')->getData();
        }
        else {
            $search = "";
            $fonction = "";
            $date_affectation = "";
        }

        // On récupère la requête des affectations pour le restaurant
        $queryBuilder = $restaurantRepository->searchAffectations($restaurant, $search, $fonction, $date_affectation, $em, true);

        // Utiliser KnpPaginator pour paginer les résultats
        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
        );

        // Création du formulaire
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        // Si le formulaire a été soumis et qu'il est balide
        if ($form->isSubmitted() && $form->isValid()) {
            // On récupère la photo
            $image = $form->get('photo')->getData();
            // Si une photo est bien présente
            if ($image) {
                // On récupère le fichier
                $nomFichier = uniqid().'.'.$image->guessExtension();
                $image->move(
                    $this->getParameter('images_directory_restaurant'),
                    $nomFichier
                );

                // On supprime l'ancienne photo
                $filesystem->remove($this->getParameter('images_directory_article').'/'.$restaurant->getPhoto($nomFichier));

                // On attache la photo au restaurant
                $restaurant->setPhoto($nomFichier);
            }

            // Insertion en base de données
            // On utilise l'entity manager
            $em->persist($restaurant);
            $em->flush();
            //On ajoute un message flash
            $this->addFlash('success','Le restaurant a été modifié avec succès');
            // Redirection vers la liste des restaurants
            return $this->redirectToRoute('app_accueil');
        }

        return $this->render('restaurant/edit.html.twig', [
            'form' => $form,
            'formSearch' => $formSearch,
            'restaurant' => $restaurant,
            "pagination" => $pagination,
        ]);
    }

    /**
     * Suppression d'un restaurant
     */
    #[Route('/{id}', name: 'restaurant_delete', methods: ['DELETE'])]
    public function delete(Restaurant $restaurant, Request $request, EntityManagerInterface $em): JsonResponse
    {
        // On récupère les données JSON
        $data = json_decode($request->getContent(), true);

        // On vérifie le token CSRF
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $data['_token'])) {
            // On supprime le restaurant
            $em->remove($restaurant);
            $em->flush();

            //On ajoute un message flash
            $this->addFlash('success','Le restaurant a été supprimé avec succès');

            // On créé le retour
            $response = [
                'status' => 'success',
                'redirect' => '/restaurant'
            ];
        } else {
            //On ajoute un message flash
            $this->addFlash('error','Le restaurant n\'a pas pu être supprimé');
            // On créé le retour
            $response = [
                'status' => 'error',
            ];
        }

        return new JsonResponse($response);
    }

    /**
     * Affecter un collaborateur dans un restaurant
     */
    #[Route('/{id}/affectations/add', name: 'restaurant_affected')]
    public function affected(Restaurant $restaurant, Request $request, EntityManagerInterface $em): Response
    {
        // Création du formulaire
        $affectation = new Affectation();
        $form = $this->createForm(AffectationType::class,$affectation);
        $form->handleRequest($request);

templates/restaurant/_restaurant.html.twig
<article class="large-6-12 flex gap justify-between">
	<div class="large-6-12">
		<img class="responsive" src="{{ asset(images_affichage_directory_restaurant ~ restaurant.photo) }}" alt="">
	</div>
	<div class="description-article large-6-12 flex gap direction-column justify-center">
		<h3>{{ restaurant.nom }}</h3>
		<p>{{ restaurant.adresse }}<br/>{{restaurant.codePostal ~ " " ~ restaurant.ville }}</p>
		<div class="flex gap justify-end">
			<a class="button secondary" href="{{path('restaurant_detail',{ "id": restaurant.id })}}" title="Voir les informations sur le restaurant {{ restaurant.nom }}">Voir</a>
		</div>
	</div>
</article>

templates/restaurant/affected.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full flex gap direction-column align-center">
    <h1>Affecter un collaborateur au {{ restaurant.nom }}</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('restaurant_edit',{ "id": restaurant.id }) }}" title="Retour au restaurant">Retour au restaurant</a>
    </div>
    <div class="large-4-12">
        {{ form_start(form) }}
        {{ form_row(form.collaborateur) }}
        {{ form_row(form.fonction) }}
        {{ form_row(form.dateDebut) }}
        {{ form_widget(form._token) }}
        {{ form_row(form.submit) }}
        {{ form_end(form, {'render_rest': false}) }}
    </div>
</div>
{% endblock %}

templates/restaurant/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full flex gap direction-column align-center">
    <h1>Nos restaurants</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('app_accueil') }}" title="Retour à la liste">Retour à la liste</a>
    </div>
    <div class="large-6-12">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    </div>
</div>
{% endblock %}

templates/restaurant/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full flex gap direction-column align-center">
    <h1>Restaurant {{ restaurant.nom }}</h1>
    <div class="large-12-12 flex gap justify-between">
        <a class="button secondary" href="{{ path('app_accueil') }}" title="Retour à la liste">Retour à la liste</a>
    </div>
    <div class="large-12-12 flex gap justify-between">
        <div class="large-6-12">
            <img class="responsive" src="{{ asset(images_affichage_directory_restaurant ~ restaurant.photo) }}" alt="">
        </div>
        <div class="description-article large-6-12 flex gap direction-column justify-between">
            <h2>{{ restaurant.nom }}</h2>
            <p>{{ restaurant.adresse }} {{restaurant.codePostal ~ " " ~ restaurant.ville }}</p>
            <div class="flex gap justify-end">
                {% if pagination.getTotalItemCount == 0 %}
                <a id="button_suppresion" class="button third" href="{{ path('restaurant_delete',{ "id": restaurant.id }) }}" title="Supprimer le restaurant">Supprimer</a>
                {% endif %}
                <a class="button primary" href="{{ path('restaurant_edit',{ "id": restaurant.id }) }}" title="Modifier le restaurant">Modifier</a>
            </div>
	</div>
    <div class="filtres large-12-12 flex justify-center gap">
        {{ form_start(formSearch, {'attr': {'class': 'large-11-12'}}) }}
        {{ form_row(formSearch.search, {'attr': {'placeholder': 'Nom, prénom ou email...'}}) }}
        {{ form_row(formSearch.fonction) }}
        {{ form_row(formSearch.date) }}
        {{ form_row(formSearch._token) }}
        {{ form_row(formSearch.submit) }}
        {{ form_end(formSearch, {'render_rest': false}) }}
    </div>
	<section class="liste-restaurant large-12-12 flex gap justify-between">
		{% for affectation in pagination.items %}
            {% include "affectation/_affectation.html.twig" %}
		{% endfor %}
	</section>
	<div class="navigation large-12-12 flex justify-between">
		{{ knp_pagination_render(pagination) }}
        <div>
            {% if pagination.getItemNumberPerPage > pagination.getTotalItemCount %}
            {{ pagination.getTotalItemCount }}
            {% else %}
            {{ pagination.getItemNumberPerPage }}
            {% endif %}
            Résultats par page - Total de
            {{ pagination.getTotalItemCount }}
            résultats
        </div>
	</div>
</div>
<script>
    // Récupère le jeton CSRF
    const csrfToken = '{{ csrf_token('delete' ~ restaurant.id) }}';
</script>
{% endblock %}

templates/restaurant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full  flex gap direction-column align-center">
    <h1>Nos restaurants</h1>
    <div class="large-12-12 flex gap">
        <a class="button secondary" href="{{ path('app_accueil') }}" title="Retour à la liste">Retour à la liste</a>
    </div>
    <div class="large-6-12">
        {{ form_start(form) }}
        {{ form_row(form.nom) }}
        {{ form_row(form.adresse) }}
        {{ form_row(form.code_postal) }}
        {{ form_row(form.ville) }}
        <div class="large-12-12 margin-top-20px margin-bottom-20px flex gap">
            <div class="large-6-12"><img class="responsive" src="{{ asset(images_affichage_directory_restaurant ~ restaurant.photo) }}" alt=""></div>
            <div class="large-6-12 flex align-center">{{ form_row(form.photo) }}</div>
        </div>
        {{ form_end(form) }}
    </div>
    <div class="separateur"></div>
    <div class="large-12-12 flex gap">
        <a class="button primary" href="{{ path('restaurant_affected',{ "id": restaurant.id }) }}" title="Affecter un collaborateur">Affecter un collaborateur</a>
    </div>
    <div class="filtres large-12-12 flex justify-center gap">
        {{ form_start(formSearch, {'attr': {'class': 'large-11-12'}}) }}
        {{ form_row(formSearch.search, {'attr': {'placeholder': 'Nom, prénom ou email...'}}) }}
        {{ form_row(formSearch.fonction) }}
        {{ form_row(formSearch.date) }}
        {{ form_row(formSearch._token) }}
        {{ form_row(formSearch.submit) }}
        {{ form_end(formSearch, {'render_rest': false}) }}
    </div>
	<section class="liste-restaurant large-12-12 flex gap justify-between">
		<table class="large-12-12">
            <thead>
                <tr>
                    <th>Collaborateur</th>
                    <th>Poste occupé</th>
                    <th>Date de début</th>
                    <th>Date de fin</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for affectation in pagination.items %}
                <tr>
                    <td><a href="{{ path('collaborateur_detail',{ "id": affectation.collaborateur.id }) }}" title="Fiche du collaborateur">{{ affectation.collaborateur.nom ~ " " ~ affectation.collaborateur.prenom }}</a></td>
                    <td>{{ affectation.fonction.intitule }}</td>
                    <td>{{ affectation.dateDebut |date('d-m-Y') }}</td>
                    <td>{% if affectation.dateFin is not null %}{{ affectation.dateFin |date('d-m-Y') }}{% endif %}</td>
                    <td>
                        <a href="{{ path('collaborateur_affectation_edit',{ "collaborateur": affectation.collaborateur.id, "affectation": affectation.id }) }}" title="Modifier l'affectation">
                            <img src="{{ asset('images/icons/edit.png') }}" alt="Icone de modification">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
	</section>
	<div class="navigation large-12-12 flex justify-between">
		{{ knp_pagination_render(pagination) }}
        <div>
            {% if pagination.getItemNumberPerPage > pagination.getTotalItemCount %}
            {{ pagination.getTotalItemCount }}
            {% else %}
            {{ pagination.getItemNumberPerPage }}
            {% endif %}
            Résultats par page - Total de
            {{ pagination.getTotalItemCount }}
            résultats
        </div>
	</div>
</div>
{% endblock %}

templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Wakdo - Bienvenue sur l'interface de gestion des restaurants{% endblock %}

{% block body %}
<div class="page-container container-full flex gap direction-column align-center">
    <h1>Tous nos restaurants</h1>
    <div class="large-12-12 flex gap">
        <a class="button primary" href="{{ path('restaurant_new') }}" title="Créer un nouveau restaurant">Nouveau restaurant</a>
    </div>
    <div class="filtres large-12-12 flex justify-center gap">
        {{ form_start(formSearch, {'attr': {'class': 'large-10-12'}}) }}
        {{ form_widget(formSearch.search, {'attr': {'placeholder': 'Rechercher par nom de restaurant, ville ou code postal...','class': 'large-10-12'}}) }}
        {{ form_end(formSearch) }}
    </div>
	<section class="liste-restaurant large-12-12 flex gap justify-between">
		{% for restaurant in pagination.items %}
            {% include "restaurant/_restaurant.html.twig" %}
		{% endfor %}
	</section>
	<div class="navigation large-12-12 flex justify-between">
		{{ knp_pagination_render(pagination) }}
        <div>
            {% if pagination.getItemNumberPerPage > pagination.getTotalItemCount %}
            {{ pagination.getTotalItemCount }}
            {% else %}
            {{ pagination.getItemNumberPerPage }}
            {% endif %}
            Résultats par page - Total de
            {{ pagination.getTotalItemCount }}
            résultats
        </div>
	</div>
</div>
{% endblock %}